#!/usr/bin/env python3

import os
import sys
import requests
import xml.etree.ElementTree as ET

url = sys.argv[1]

print(f"DNF Sync {url}")

r = requests.get(f"{url}/repodata/repomd.xml")
print(r.text)

root = ET.fromstring(r.text)
# print(root)

d = root.find('.//{http://linux.duke.edu/metadata/repo}data[@type="primary_db"]')
print(d.attrib)
l = d.find('{http://linux.duke.edu/metadata/repo}location')
print(l)
print(l.attrib['href'])

