#!/usr/bin/env python3

import os
import sys
import requests
import gzip
import xml.etree.ElementTree as ET

def get(url):
    # print(f'GET {url}')
    r = requests.get(url)
    return r

def href(e):
    return e.attrib['href']

def location(baseurl):
    tree = ET.fromstring(get(f"{baseurl}/repodata/repomd.xml").text)
    database = tree.find('{http://linux.duke.edu/metadata/repo}data[@type="primary"]')
    location = database.find('{http://linux.duke.edu/metadata/repo}location')
    return f"{baseurl}/{location.attrib['href']}"

def database(url):
    r = get(url)
    text = gzip.decompress(r.content)
    tree = ET.fromstring(text)
    return tree

def packages(baseurl):
    url = location(baseurl)
    doc = database(url)
    items = doc.findall('{http://linux.duke.edu/metadata/common}package')
    p = [ href(d.find('{http://linux.duke.edu/metadata/common}location')) for d in items]
    return p

def download(url, folder):
    filename = os.path.basename(url)
    path = os.path.join(folder, filename)
    if os.path.exists(path):
        print(filename)
        return
    else:
        rpm = get(url).content
        with open(path, 'wb') as f:
            f.write(rpm)
        print(f"{filename} downloaded")

def main(baseurl, folder):
    if not os.path.isdir(folder):
        os.makedirs(folder)
    for package in packages(baseurl):
        download(f"{baseurl}/{package}", folder)

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
