#!/usr/bin/env python3

import os
import sys
import requests

import xml.etree.ElementTree as ET

def get(url):
    print(f'GET {url}')
    r = requests.get(url)
    return r.text

def location(baseurl):
    tree = ET.fromstring(get(f"{baseurl}/repodata/repomd.xml"))
    database = tree.find('{http://linux.duke.edu/metadata/repo}data[@type="primary"]')
    location = database.find('{http://linux.duke.edu/metadata/repo}location')
    return f"{baseurl}/{location.attrib['href']}"

def database(url):
    doc = ET.fromstring(get(url))
    print(doc)

def packages(baseurl):
    url = location(baseurl)
    doc = database(url)
    return ['foo','bar']

def main(baseurl):
    for package in packages(baseurl):
        print(package)

if __name__ == '__main__':
    main(sys.argv[1])
